### login user
POST http://localhost:3002/auth/login HTTP/1.1
content-type: application/json

{
    "username": "sample2",
    "password": "sample"
   
}

### GET profile
GET http://localhost:3002/auth/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZTIiLCJzdWIiOiJlZmMyZDlkZi03NjZmLTRmYzktODg0OC1jNmY4OGIwZDRjMzAiLCJpYXQiOjE2MTQ2NDk0NzEsImV4cCI6MTYxNDgyMjI3MX0.86se5-kGm6BY0VELzKQLnXeAiHWeok7p5S57SZZ-Tsk