### create post
POST https://nest-blog-app.wilsonpc.repl.co/blog HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsInN1YiI6IjgxMWQ1MmJkLWY4OWMtNDliOC1hMzc1LTllNWQ3MDFlNWFiYyIsImlhdCI6MTYxNDgyMDU4NiwiZXhwIjoxNjE0OTkzMzg2fQ.TN4v4o6jaey6Q87T9PiF11O2XtHB2_6CYF9wxZxwOpU

{
    "authorId": "811d52bd-f89c-49b8-a375-9e5d701e5abc",
    "content":"The render method will be called each time an update happens, but as long as we render <Clock /> into the same DOM node, only a single instance of the Clock class will be used. This lets us use additional features such as local state and lifecycle methods.",
    "title":"Segundo post"
}

### update post
PUT http://localhost:3002/blog/bbfe2a24-2eb1-4337-bac6-d50bb11804e7 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZTIiLCJzdWIiOiJlZmMyZDlkZi03NjZmLTRmYzktODg0OC1jNmY4OGIwZDRjMzAiLCJpYXQiOjE2MTQ2NDk0NzEsImV4cCI6MTYxNDgyMjI3MX0.86se5-kGm6BY0VELzKQLnXeAiHWeok7p5S57SZZ-Tsk

{
    "title": "sample2"
   
}

### GET post
GET http://localhost:3002/blog/ HTTP/1.1
content-type: application/json

### GET post
GET http://localhost:3002/blog/bbfe2a24-2eb1-4337-bac6-d50bb11804e7 HTTP/1.1
content-type: application/json
